sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - dmd
script:
 - make test DCOMPILER=$DC
 - if [[ -z "$TRAVIS_TAG" || "$TRAVIS_TAG" == "" ]]; then
     export USE_VERSION="v~dev"; else
     export USE_VERSION="$TRAVIS_TAG";
   fi
 - make package DCOMPILER=$DC OS=$TRAVIS_OS_NAME APP_VERSION=$USE_VERSION
 - echo "Done"
 
